FIX: Remove sha part

diff --git a/.github/workflows/ci-workflow.yaml b/.github/workflows/ci-workflow.yaml
--- a/.github/workflows/ci-workflow.yaml
+++ b/.github/workflows/ci-workflow.yaml
@@ -16,30 +16,30 @@ jobs:
         node-version: ['18.x', '20.x']
 
     steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
+    - uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: ${{ matrix.node-version }}
-          cache: 'yarn'
+    - name: Set up Node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: 'yarn'
 
-      - name: Check Node.js version
-        run: node -v
+    - name: Check Node.js version
+      run: node -v
 
-      - name: Install dependencies
-        run: yarn install --frozen-lockfile
+    - name: Install dependencies
+      run: yarn install --frozen-lockfile
 
-      - name: Lint code
-        run: yarn lint:all
+    - name: Lint code
+      run: yarn lint:all
 
-      - name: Build projects
-        run: yarn build:all
+    - name: Build projects
+      run: yarn build:all
 
-      - name: Test projects
-        run: yarn test:all
+    - name: Test projects
+      run: yarn test:all
 
   validate_commit_messages:
     runs-on: ubuntu-latest
@@ -56,23 +56,17 @@ jobs:
           fi
       - name: Validate Commit Messages
         run: |
-          BASE_SHA=$(git rev-parse ${{ github.event.before }} || echo "fallback")
-          HEAD_SHA=$(git rev-parse ${{ github.event.after }} || echo "fallback")
-          if [ "$BASE_SHA" = "fallback" ] || [ "$HEAD_SHA" = "fallback" ]; then
-            echo "Fallback: Unable to validate commit range."
-            exit 0  # Optionally adjust this as needed for your project
-          else
-            commit_messages=$(git log --format=%s $BASE_SHA..$HEAD_SHA)
-            echo "Checking commit messages: $commit_messages"
-            IFS=$'\n'
-            for message in $commit_messages; do
-              if ! echo "$message" | grep -Pq '^(ADD:|FIX:|DEL:|UPD:) .+'; then
-                echo "Invalid commit message: '$message'"
-                echo "Commit messages must start with ADD:, FIX:, DEL:, or UPD: followed by a space and text."
-                exit 1
-              fi
-            done
-            echo "All commit messages adhere to the specified format."
+          commit_messages=$(git log --format=%s ${{ github.event.before }}..${{ github.event.after }})
+          echo "Checking commit messages: $commit_messages"
+          IFS=$'\n'
+          for message in $commit_messages; do
+            if ! echo "$message" | grep -Pq '^(ADD:|FIX:|DEL:|UPD:) .+'; then
+              echo "Invalid commit message: '$message'"
+              echo "Commit messages must start with ADD:, FIX:, DEL:, or UPD: followed by a space and text."
+              exit 1
+            fi
+          done
+          echo "All commit messages adhere to the specified format."
 
   validate_branch_names:
     runs-on: ubuntu-latest
